from tkinter import *
root = Tk()
root.title("اولين برنامه ويندوزي من ")
Label(root,text='نام و نام خانوادگي',fg='yellow',bg='brown',font ='Zar 18 bold ').pack(side='right')
root.configure(background='black')
root.geometry('500x300')
T = Text(root,height =2 ,width = 30).pack(side='right')
#T.insert(END,"If that address is correct Try again later.\n Check your network connection.\n")
logo.pack()
root.mainloop()
